#current and planned paramters have the same keys but different values because they are the ones changing in the retrofit

mc_params = {"uncertainty_advanced_flag": -1, "confidence_level": 95, #["uncertainty_advanced_flag": -1] used in get_noise is used in an "if" function. The value "-1" makes the "else" blok run, computing the noisematrix
                "noise_flag": 2, "geometry_noise_check": 1,
                "pv_panel_noise_check" : 1, "pv_panel_confidence": 10,
                "geometry_confidence": 10, "number_of_monte_carlo_runs": 1500,
                "thermal_prop_noise_check": 1, "thermal_prop_confidence": 10,
                "efficiencies_noise_check": 1,
                "efficiencies_confidence": 5,
                "simplified_DHW_load_noise_check": 1,
                "simplified_DHW_load_confidence": 10,
                "environment_noise_check": 1, "environment_confidence": 20,
                "investment_noise_check": 1, "investment_confidence": 10,
                "energy_cost_noise_check": 1, "energy_cost_confidence_today": 1, "energy_cost_confidence_final": 10,
                "Uwall_noise_check": 1, "Uwall_confidence": 15,
                "Uroof_noise_check": 1, "Uroof_confidence": 15,
                "Ufloor_noise_check": 1, "Ufloor_confidence": 15,
                "Sfloor_noise_check": 1, "Sfloor_confidence": 15,
                "sd_vol_ratio_noise_check": 1, "sd_vol_ratio_confidence": 7,
                "wall_height_noise_check": 1, "wall_height_confidence": 5,
                "Uwindows_noise_check": 1, "Uwindows_confidence": 15,
                "window_floor_ratio_noise_check": 1,
                "window_floor_ratio_confidence": 6,
                "wall_thermal_conductivity_noise_check": 1,
                "wall_thermal_conductivity_confidence": 7,
                "wall_thickness_noise_check": 1,
                "wall_thickness_confidence": 4,
                "roof_thermal_conductivity_noise_check": 1,
                "roof_thermal_conductivity_confidence": 3,
                "roof_thickness_noise_check": 1,
                "roof_thickness_confidence": 5,
                "floor_thermal_conductivity_noise_check": 1,
                "floor_thermal_conductivity_confidence": 8,
                "floor_thickness_noise_check": 1,
                "floor_thickness_confidence": 2,
                "he_conv_noise_check": 1, "he_conv_confidence": 8,
                "shadow_noise_check": 1, "shadow_confidence": 35,
                "sun_factor_noise_check": 1, "sun_factor_confidence": 15,
                "alfa_plaster_noise_check": 1,
                "alfa_plaster_confidence": 7,
                "air_change_noise_check": 1, "air_change_confidence": 30,
                "advanced_DHW_load_noise_check": 1,
                "advanced_DHW_load_confidence": 7,
                "regulation_eff_noise_check": 1,
                "regulation_eff_confidence": 4,
                "distribution_eff_noise_check": 1,
                "distribution_eff_confidence": 4,
                "emission_eff_noise_check": 1,
                "emission_eff_confidence": 9,
                "heating_solar_fraction_noise_check": 1,
                "heating_solar_fraction_confidence": 22,
                "heating_burner_eff_noise_check": 1,
                "heating_burner_eff_confidence": 6,
                "heating_pellet_eff_noise_check": 1,
                "heating_pellet_eff_confidence": 5,
                "heating_heat_pump_COP_noise_check": 1,
                "heating_heat_pump_COP_confidence": 19,
                "DHW_solar_fraction_noise_check": 1,
                "DHW_solar_fraction_confidence": 11,
                "DHW_burner_eff_noise_check": 1,
                "DHW_burner_eff_confidence": 7,
                "DHW_electric_boiler_eff_noise_check": 1,
                "DHW_electric_boiler_eff_confidence": 14,
                "DHW_heat_pump_COP_noise_check": 1,
                "DHW_heat_pump_COP_confidence": 12,
                "HDD_noise_check": 1, "HDD_confidence": 22,
                "solar_RAD_noise_check": 1, "solar_RAD_confidence": 18,
                "heating_days_noise_check": 1,
                "heating_days_confidence": 14,
                "discount_rate_noise_check": 1,
                "discount_rate_confidence": 7,
                "fixed_costs_noise_check": 1, "fixed_costs_confidence": 15,
                "fuel_cost_noise_check": 1, "fuel_cost_confidence_today": 1, "fuel_cost_confidence_final": 3,
                "electric_cost_noise_check": 1,
                "electric_cost_confidence_today": 1, "electric_cost_confidence_final": 6,
                "pellet_cost_noise_check": 1, "pellet_cost_confidence_today": 1,
                "pellet_cost_confidence_final": 11,
                "incentives_check": -1, "incentives_amount_%": 60,
                "incentives_refund_years": 15,
                "loan_check": -1, "loan_amount_%": 85,
                "loan_refund_years": 20, "loan_rate": 5,
                "time_horizon_years": 25, "min_Epsav": "", "min_Esav": 10,
                "min_NPV": 1000, "min_IRR": 3, "min_Dpayback": 30,
                "min_loss_risk": 15,
                "min_churn_rate": 20, "min_default_rate": 3, "max_Epsav": "",
                "max_Esav": 75,
                "max_NPV": 15000, "max_IRR": 17, "max_Dpayback": 11,
                "max_loss_risk": 5,
                "max_churn_rate": 5, "max_default_rate": 1, "weight_Epsav": "",
                "weight_Esav": 2, "weight_NPV": 5, "weight_IRR": 1,
                "weight_Dpayback": 7, "weight_loss_risk": 3,
                "weight_churn_rate": 1, "weight_default_rate": 4, "unit_option": "optionkwh"
}



common_params = {"mode": 0, "dwelling_count": 1, "floor_count": 1, "n_occupants": 1,
                           "country": "Ireland", "city": "Maynooth", "building_type": "detached house",
                           "building_year": "1946-1960", "floor_area": 151,
                           "storey_position": "mid", "wall_thermal_transmittance": 2.1,
                           "roof_thermal_transmittance": 0.68,
                           "floor_thermal_transmittance": 0.69,
                           "total_surface_area_to_volume_ratio": 0.60, "wall_height": 3.8,
                           "discount_rate": 8, "churn_rate": 0, "churn_rate_95": 0,
                           "default_churn_rate": 0, "default_churn_rate_95": 0}  #paramaters that do not change when calculation both current and planned cases


# available "heating_type": 1-3, "burner_type": 1-3, "emitter_type": 1-6, "fuel_type": 1-4, "DHW_type": 0-3, "DHW_burner_type": 1-3, "panel_type": 1-3

current_params={"heating_type": 1, "burner_type": 1, "emitter_type": 1, "fuel_type": 1,
                            "solar_check": 0, "solar_perc": 0, "DHW_type": 2,
                            "DHW_burner_type": 1, "DHW_solar_check": 0, "DHW_solar_perc": 0,
                            "wall_insulation_check": 0, "roof_insulation_check": 0,
                            "floor_insulation_check": 0, "wall_envelope_thermal_conductivity": 0.05,
                            "wall_thickness": 0.1, "roof_envelope_thermal_conductivity": 0.08,
                            "roof_thickness": 0.1, "floor_envelope_thermal_conductivity": 0.04,
                            "floor_thickness": 0.1, "window_flag": "",
                            "window_transmittance_value": 4.9,
                            "window_to_surface_area_ratio": 0.08,
                            "cooling_system_type": 3, "panel_type": 0, "target_pv_fraction": 1, "pv_roof_utilization_ratio": 0.7}

planned_params={"heating_type": 3, "burner_type": 1, "emitter_type": 1, "fuel_type": 4,
                            "solar_check": 0, "solar_perc": 0, "DHW_type": 0,
                            "DHW_burner_type": 3, "DHW_solar_check": 0, "DHW_solar_perc": 0,
                            "wall_insulation_check": 0, "roof_insulation_check": 0,
                            "floor_insulation_check": 0, "wall_envelope_thermal_conductivity": 0.03,
                            "wall_thickness": 0.1, "roof_envelope_thermal_conductivity": 0.03,
                            "roof_thickness": 0.1, "floor_envelope_thermal_conductivity": 0.03,
                            "floor_thickness": 0.1, "window_flag": "",
                            "window_transmittance_value": 4.9,
                            "window_to_surface_area_ratio": 0.08,
                            "cooling_system_type": 3, "panel_type":1, "target_pv_fraction": 1, "pv_roof_utilization_ratio": 0.7}



case = {'common_params': common_params,
        'current_params': current_params,
        'planned_params': planned_params}

